/* ============================================================
   NCEA LEVEL 1 — standards data
   Loaded on demand by whs-ncea-engine.html. Keep this file in
   the same folder as the engine.

   NOTE ON SHELF LIFE: these are the new-style Level 1 standards
   introduced in 2024 — four per subject, 5 credits each. NCEA
   Level 1 is scheduled to be replaced in 2028, so expect to
   rewrite this file rather than amend it.

   To add a subject: copy a subject block and swap the standards.
   To add it to a faculty: add its name to that faculty's
   subjects list below.

   verified:true  = code / title / credits / internal-external
   confirmed against NZQA or ncea.education.govt.nz.
   Teaching fields are drafts for the subject teacher to review.
   ============================================================ */
(function () {

const FACULTIES = [
 { name:'Social Sciences', dark:'#7900CC', light:'#F5EFFF', subjects:['Geography','History'] },
 { name:'Science',         dark:'#007040', light:'#E4F4E5', subjects:['Science','Chemistry and Biology','Physics, Earth and Space Science'] },
 { name:'Maths',           dark:'#9F1559', light:'#F8E7EE', subjects:[] },
 { name:'English',         dark:'#22229D', light:'#EBF5FA', subjects:[] },
 { name:'Māori',           dark:'#1A6ABE', light:'#ECFBFF', subjects:[] },
 { name:'Technology',      dark:'#DB2026', light:'#FDECE7', subjects:[] },
 { name:'Arts',            dark:'#9A6300', light:'#FFF7EE', subjects:[] },
 { name:'PE & Health',     dark:'#BF0000', light:'#FFEDED', subjects:[] }
];

const SUBJECTS = {

'Geography':{
  lens:'Level 1 Geography is built around te taiao and the interconnections between whenua, wai, āhuarangi and koiora, and asks "What is where, why there, and why care?" The four Big Ideas are: te taiao is interconnected with ngā tangata; te taiao can be shaped by natural processes; tikanga informs the relationships between ngā tangata and te taiao; and perspectives and power influence te taiao. The subject focuses on Aotearoa New Zealand and the wider Pacific.',
  discipline:'Geography reasons from located evidence. Every claim needs a place, and most need a figure and a date. At Level 1 the step up from describing to explaining is what separates Achieved from Merit — say how and why, not just what.',
  verifyNote:'Four standards, 5 credits each, 20 credits in total — two internal and two external. Evidence for the internals may be presented in te reo Māori, English, or New Zealand Sign Language.',
  standards:[
  { code:'91932', ref:'1.1', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of the spatial distribution of a phenomenon and its impacts on place',
    bigIdea:'Find where something is happening, work out the pattern in where it is, and show what it does to those places.',
    format:'Internally assessed. Evidence may be an extended task, an investigation, digital evidence such as recorded interviews, photographs or film, or a portfolio. Your teacher may only give GENERAL feedback during the assessment — work that has received sustained or detailed feedback cannot be submitted. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'Named places, maps showing the distribution, figures with dates, and specific impacts on the people and environments of those places.',
    criteria:{achieved:'Demonstrate understanding of the spatial distribution of the phenomenon and its impacts on place.',
      merit:'Demonstrate in-depth understanding — explain the pattern of distribution and how the impacts occur.',
      excellence:'Demonstrate comprehensive understanding — explain the relationships between the distribution, its causes and its impacts.'},
    bandShift:{aToM:'Explain WHY the phenomenon is distributed the way it is, and HOW it produces its impacts — not just where it is and what happens.',
      mToE:'Connect the distribution, its causes and its impacts into one account, and show how the impacts differ between places.'},
    verbs:['describe','explain','identify','show understanding'],
    topics:['Spatial distribution and pattern','Mapping a phenomenon','Scale: local, regional, national','Impacts on place','Impacts on people','Change over time','Geographic terminology'],
    contexts:['A phenomenon agreed with your kaiako — often a hazard, a land use, a population pattern, or an environmental change in Aotearoa or the Pacific'],
    misconceptions:['Describing the phenomenon rather than its distribution — the pattern of WHERE it occurs is the point.',
      'Treating a map as decoration rather than as the evidence for the pattern.',
      'Assuming impacts are the same everywhere the phenomenon occurs.'],
    pitfalls:['Maps without a title, key, scale or north arrow.',
      'General statements with no named places or figures.',
      'Impacts listed with no explanation of how the phenomenon causes them.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'91933', ref:'1.2', credits:5, mode:'internal', verified:true,
    title:'Explore an environment using data',
    bigIdea:'Collect real data about a real place, turn it into something you can see, and work out what it tells you.',
    format:'Internally assessed. Your evidence MUST include data that you have processed and presented yourself into an appropriate visual, and that visual must be accurate. Your teacher may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language. This standard can also contribute to the numeracy or pāngarau co-requisite during the transition period.',
    evidence:'Your own collected or sourced data, processed by you, presented in an accurate visual — map, graph or diagram — with conclusions drawn from what the visual shows.',
    criteria:{achieved:'Explore an environment using data, presenting it appropriately.',
      merit:'Explore in depth — process and present data accurately and explain what it shows about the environment.',
      excellence:'Explore comprehensively — connect the data to the geographic processes and features of the environment.'},
    bandShift:{aToM:'Explain what the data actually shows about the environment, rather than presenting it and stopping.',
      mToE:'Link what the data shows to the geographic processes shaping the environment.'},
    verbs:['collect','process','present','describe','explain'],
    topics:['Collecting primary data','Using secondary data','Choosing an appropriate visual','Maps, graphs and diagrams','Accuracy in presentation','Drawing conclusions from data','Fieldwork techniques'],
    contexts:['An environment agreed with your kaiako — often local fieldwork'],
    misconceptions:['Thinking any graph will do — the visual has to suit the data you collected.',
      'Believing the data speaks for itself without you explaining what it shows.',
      'Treating accuracy as optional when the standard requires the visual to be accurate.'],
    pitfalls:['A visual produced by software without you processing the data yourself.',
      'Axes, keys or units missing, which makes the visual inaccurate.',
      'Data presented but never interpreted.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'91934', ref:'1.3', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of how natural processes shape an environment',
    bigIdea:'Show how nature builds and changes a place — the processes at work, and what they produce.',
    format:'End-of-year examination. You study one environment shaped by natural processes and answer questions about it, often supported by resource material.',
    evidence:'A named New Zealand or Pacific environment, the natural processes named correctly, and specific landforms or features linked to the processes that made them.',
    criteria:{achieved:'Demonstrate understanding of how natural processes shape an environment.',
      merit:'Demonstrate in-depth understanding — explain how the processes operate and what they produce.',
      excellence:'Demonstrate comprehensive understanding — explain how the processes interact and how the environment changes over time.'},
    bandShift:{aToM:'Explain HOW the process works step by step and what feature it creates, rather than naming processes.',
      mToE:'Show the processes interacting with each other, and how the environment has changed over time as a result.'},
    verbs:['identify','describe','explain'],
    topics:['Fluvial processes and river landforms','Coastal processes and landforms','Volcanic and tectonic processes','Glacial processes','Weathering, erosion, transport and deposition','Interaction between processes','Change over time','Pūrākau and science as ways of understanding formation'],
    contexts:['One environment studied in class, in Aotearoa New Zealand or the wider Pacific'],
    misconceptions:['Using weathering and erosion as if they mean the same thing.',
      'Saying a process "makes" a landform without explaining the steps in between.',
      'Assuming natural processes work at a constant rate.',
      'Treating the environment as finished rather than still changing.'],
    pitfalls:['Processes named with no explanation of how they work.',
      'No named environment or landforms.',
      'Diagrams drawn but not labelled or annotated.',
      'Writing everything known about the environment instead of answering the question asked.'] },

  { code:'91935', ref:'1.4', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of decision-making in response to a geographic challenge in the wider Pacific region',
    bigIdea:'A real challenge in the Pacific, real people deciding what to do about it — show who decided, why, and what followed.',
    format:'End-of-year examination. The context is the wider Pacific region, and questions focus on the decision-making rather than only the challenge itself.',
    evidence:'The challenge named and located, the groups involved named with their perspectives, the decision described, and its consequences evidenced.',
    criteria:{achieved:'Demonstrate understanding of decision-making in response to a geographic challenge in the wider Pacific region.',
      merit:'Demonstrate in-depth understanding — explain the perspectives behind the decisions and their consequences.',
      excellence:'Demonstrate comprehensive understanding — explain how perspectives and power shaped the decision and its outcomes.'},
    bandShift:{aToM:'Explain the perspectives behind each group\u2019s position, and how the decision produced its consequences.',
      mToE:'Show how differences in POWER shaped whose perspective prevailed — this is the Big Idea the standard is built on.'},
    verbs:['identify','describe','explain'],
    topics:['Geographic challenges in the Pacific','Climate change and sea level rise','Resource use and management','Perspectives and values','Power and who gets to decide','Consequences of decisions','Kaitiakitanga and tikanga in decision-making'],
    contexts:['A geographic challenge in the wider Pacific region studied in class'],
    misconceptions:['Treating all groups as having equal say, when power differences are central to this standard.',
      'Confusing a perspective (the values behind a view) with a viewpoint (what someone thinks).',
      'Presenting Pacific communities as passive rather than as decision-makers.'],
    pitfalls:['The challenge described at length with the decision-making barely covered.',
      'Groups referred to generally rather than named.',
      'No consideration of power, which is where the higher grades sit.',
      'Consequences asserted without evidence.'] }
  ]},

'History':{
  lens:'Level 1 History is built around whanaungatanga, vā and fonua, and around historical concepts used as lenses on the past — cause and effect, continuity and change, significance, and perspectives. The focus is contexts of significance to Aotearoa New Zealand, and mātauranga Māori concepts sit alongside historical ones.',
  discipline:'History reasons from evidence to argument. Every claim is dated and attributed, sources are interrogated rather than quoted, and what happened is kept separate from how people have interpreted it.',
  verifyNote:'Four standards, 5 credits each, 20 credits in total — two internal and two external. AS92025 and AS92026 are on the approved list for the literacy co-requisite during the transition period.',
  standards:[
  { code:'92024', ref:'1.1', credits:5, mode:'internal', verified:true,
    title:'Engage with a variety of primary sources in a historical context',
    bigIdea:'Get your hands on real sources from the past — objects, photographs, letters, oral traditions — and work out what each one can actually tell you.',
    format:'Internally assessed. Evidence may be an extended task, an investigation, digital evidence, or a portfolio. Your kaiako may only give GENERAL feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'Several DIFFERENT types of primary source, each identified by type, with what it shows and its limitations, selected deliberately for your focus question.',
    criteria:{achieved:'Engage with a variety of primary sources in a historical context, identifying and describing them.',
      merit:'Engage in depth — select appropriate sources for a focus question and explain what they show.',
      excellence:'Engage comprehensively — identify the main ideas across sources and explain how they answer the focus question.'},
    bandShift:{aToM:'Choose your sources deliberately for the focus question, and explain what each one actually shows, instead of describing whatever you found.',
      mToE:'Draw the main ideas out ACROSS several sources and show how together they answer the focus question.'},
    verbs:['identify','describe','select','explain'],
    topics:['Types of primary source: oral history traditions, artefacts, photographs, documents','Primary versus secondary sources','Writing a focus question','Selecting sources for a purpose','What a source can and cannot tell you','Mātauranga Māori concepts as sources of understanding'],
    contexts:['A historical context of significance to Aotearoa New Zealand, agreed with your kaiako — often local'],
    misconceptions:['Thinking primary means old — a source is primary relative to the event, not to today.',
      'Treating oral history traditions as less reliable than written documents rather than as a different kind of evidence.',
      'Assuming a source has to be truthful to be useful — an inaccurate source still shows what people believed.'],
    pitfalls:['Only one type of source used, when the standard asks for a variety.',
      'Sources described but never connected to the focus question.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92025', ref:'1.2', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of the significance of a historical context',
    bigIdea:'Take one piece of the past and argue why it mattered — to the people then, and to us now.',
    format:'Internally assessed, and on the approved list for the literacy co-requisite during the transition period. Your kaiako may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'Dated specifics, named people and groups, and reasons for significance supported by evidence rather than asserted.',
    criteria:{achieved:'Demonstrate understanding of the significance of a historical context, describing why it matters.',
      merit:'Demonstrate in-depth understanding — explain the reasons for its significance, supported by evidence.',
      excellence:'Demonstrate comprehensive understanding — explain significance for different groups and over time.'},
    bandShift:{aToM:'Explain WHY it was significant with evidence behind each reason, rather than stating that it was important.',
      mToE:'Show that significance differs — for different groups at the time, and between then and now.'},
    verbs:['describe','explain','show understanding'],
    topics:['What makes something historically significant','Significance at the time versus since','Significance for different groups','Consequences and legacy','Using evidence to support a claim','Structuring a written explanation'],
    contexts:['A historical context of significance to Aotearoa New Zealand, agreed with your kaiako'],
    misconceptions:['Equating significance with fame or size rather than with consequence and meaning.',
      'Assuming an event was significant to everyone in the same way.',
      'Believing significance is a fact to be recalled rather than an argument to be made.'],
    pitfalls:['Significance asserted with no reasons or evidence.',
      'A narrative of what happened instead of an argument about why it mattered.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92026', ref:'1.3', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of historical concepts in contexts of significance to Aotearoa New Zealand',
    bigIdea:'Use the historian\u2019s tools — cause and effect, change, significance, perspectives — on both a context you have studied and one you have never seen.',
    format:'End-of-year examination, and on the approved list for the literacy co-requisite. You are expected to write an explanation covering BOTH a familiar context you have learned AND an unfamiliar one presented through sources in the paper. Note that submitted reports were removed as a method of external assessment at Level 1 from 2025.',
    evidence:'Specific historical detail — names, dates, places, figures — used to support each concept, plus evidence read directly from the unfamiliar sources supplied.',
    criteria:{achieved:'Identify and describe historical concepts using relevant evidence, in familiar and unfamiliar contexts.',
      merit:'Explain historical concepts, using evidence to back up the points being made.',
      excellence:'Explain comprehensively — use evidence to develop the explanation so it strengthens the argument.'},
    bandShift:{aToM:'Move from describing a concept to explaining it, with evidence chosen to back up each point.',
      mToE:'Use the evidence to DEVELOP the explanation rather than just support it — build the argument with it.'},
    verbs:['identify','describe','explain'],
    topics:['Cause and effect','Continuity and change','Historical significance','Perspectives','Applying concepts to an unfamiliar context','Structuring a written explanation','Using historical evidence'],
    contexts:['A familiar context studied in class, plus an unfamiliar context supplied in the examination'],
    misconceptions:['Believing prior knowledge will carry the unfamiliar section — the concepts and the supplied sources do that work.',
      'Treating chronology as causation: that one thing followed another does not show it caused it.',
      'Confusing a perspective with an opinion.'],
    pitfalls:['The unfamiliar context answered from general knowledge rather than from the sources given.',
      'Concepts named but never applied to the actual context.',
      'Evidence dropped in without being connected to the point being made.'] },

  { code:'92027', ref:'1.4', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of perspectives on a historical context',
    bigIdea:'People living through the same events saw them completely differently. Work out who saw what, and why.',
    format:'End-of-year examination. Sources presenting different perspectives are supplied in the paper.',
    evidence:'Perspectives attributed to named people or groups and dated, with what shaped each one identified from the sources.',
    criteria:{achieved:'Demonstrate understanding of perspectives on a historical context, describing them.',
      merit:'Demonstrate in-depth understanding — explain what shaped the different perspectives.',
      excellence:'Demonstrate comprehensive understanding — explain how and why perspectives differ, using evidence.'},
    bandShift:{aToM:'Explain what shaped each perspective — position, interest, and the information available to that person.',
      mToE:'Explain how and why the perspectives differ from each other, and what that reveals about the context.'},
    verbs:['identify','describe','explain'],
    topics:['What a perspective is','What shapes a perspective','Perspectives of people at the time','Later interpretations','Comparing perspectives','Perspectives in mātauranga Māori'],
    contexts:['A historical context of significance to Aotearoa New Zealand, with sources supplied in the examination'],
    misconceptions:['Treating perspective as personal opinion rather than a position shaped by circumstance and interest.',
      'Judging people of the past by present-day values without acknowledging you are doing it.',
      'Assuming there were only two perspectives on any event.'],
    pitfalls:['Perspectives listed side by side with no explanation of why they differ.',
      'Positions described without saying whose they were.',
      'Answering from memory instead of from the sources supplied.'] }
  ]},

'Science':{
  lens:'Level 1 Science is about how science actually works — how ideas develop, how claims are tested, and how science informs decisions in a local context. It is as much about the nature of science as about content.',
  discipline:'Science reasons from evidence. A science IDEA is a relationship, theory or model that explains a phenomenon — not an observation or a fact. Level 1 keeps asking you to tell those apart.',
  verifyNote:'Four standards, 5 credits each, 20 credits — two internal, two external. Note that Level 1 Science splits into several subjects: Science, Chemistry and Biology (ChemBio), Physics Earth and Space Science (PESS), and Agricultural and Horticultural Science.',
  standards:[
  { code:'91920', ref:'1.1', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of a science-informed response to a local issue',
    bigIdea:'Take a real issue in your area, work out the science behind it, and look at how people are responding — including who holds which view.',
    format:'Internally assessed. Your kaiako may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'A science IDEA described — a relationship, theory or model, not an observation — plus a second perspective held by a PARTICULAR group, a named science-informed response, and understanding of tiakitanga as responsible science practice.',
    criteria:{achieved:'Describe a science idea relevant to the issue, outline a second perspective held by a particular group, and identify a science-informed response.',
      merit:'Explain the science idea and how it informs the response, with detail.',
      excellence:'Explain comprehensively — link the science, the perspectives and the response, and evaluate the response.'},
    bandShift:{aToM:'Explain how the science idea actually informs the response, rather than describing them separately.',
      mToE:'Bring the science, the perspectives and the response together, and judge how well the response addresses the issue.'},
    verbs:['describe','outline','identify','explain'],
    topics:['What counts as a science idea','Local issues with a science dimension','Perspectives held by particular groups','Science-informed responses','Tiakitanga and responsible science practice','Evaluating a response'],
    contexts:['A local issue agreed with your kaiako — for example predator control and 1080, water quality, or coastal erosion'],
    misconceptions:['Describing an observation or a fact and calling it a science idea — an idea is a relationship, theory or model.',
      'Attributing a perspective to "the public" or "some people" rather than to a particular identified group.',
      'Treating tiakitanga as an add-on rather than as part of responsible science practice.'],
    pitfalls:['A science idea that is really just a description of what happens.',
      'A second perspective from an individual or a vague broad group rather than a particular one.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'91921', ref:'1.2', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of the use of a range of scientific investigative approaches in a context',
    bigIdea:'Scientists do not only do fair-test experiments. Show you understand the different ways science actually investigates things.',
    format:'Internally assessed. Your kaiako may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'Several DIFFERENT investigative approaches named and described, each with what it is good for and what it cannot tell you, applied to the actual context.',
    criteria:{achieved:'Describe a range of scientific investigative approaches used in the context.',
      merit:'Explain why particular approaches suit particular questions in the context.',
      excellence:'Explain comprehensively — link the approaches, their strengths and limitations, and what they contribute together.'},
    bandShift:{aToM:'Explain WHY each approach suits the question being asked, rather than describing what it is.',
      mToE:'Show how the approaches complement each other, and what each can and cannot establish.'},
    verbs:['describe','explain','compare'],
    topics:['Fair testing','Pattern seeking','Classifying and identifying','Modelling','Exploring over time','Using secondary data','Strengths and limitations of each approach','Mātauranga Māori approaches to observing te taiao'],
    contexts:['A scientific context agreed with your kaiako'],
    misconceptions:['Believing the fair test is the only real scientific method.',
      'Assuming an approach that cannot be controlled is unscientific — much of astronomy, geology and ecology works this way.',
      'Confusing the approach with the equipment used.'],
    pitfalls:['Only one or two approaches covered when the standard asks for a range.',
      'Approaches described generically with no link to the actual context.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'91922', ref:'1.3', credits:5, mode:'external', verified:true,
    title:'Describe features of science that have contributed to the development of a science idea in a local context',
    bigIdea:'Science ideas do not appear fully formed. Show how one actually developed — the evidence, the arguments, the people.',
    format:'End-of-year examination. Submitted reports were removed as a method of external assessment at Level 1 from 2025, so this is examined.',
    evidence:'The science idea stated precisely, the features of science named, and specific evidence and events in the idea\u2019s development, located in a real context.',
    criteria:{achieved:'Describe features of science that contributed to the development of the science idea.',
      merit:'Explain how those features contributed to its development.',
      excellence:'Explain comprehensively — link the features to each other and to how the idea changed over time.'},
    bandShift:{aToM:'Explain HOW each feature of science contributed, rather than naming features and describing the idea separately.',
      mToE:'Show the features working together and account for how and why the idea changed.'},
    verbs:['identify','describe','explain'],
    topics:['Features of science: evidence, peer review, replication, revision','Science as a community activity','How ideas change with new evidence','Tentativeness and durability of science ideas','Science in a local context','Mātauranga Māori and science as knowledge systems'],
    contexts:['A science idea developed in a local context, studied in class'],
    misconceptions:['Believing science ideas are proven once and then fixed.',
      'Treating a change in a science idea as science failing, rather than as science working.',
      'Confusing a feature of science with a step in a method.'],
    pitfalls:['The science idea described but its DEVELOPMENT never covered.',
      'Features of science listed generically with no evidence from the actual context.',
      'No named people, evidence or events in the development story.'] },

  { code:'91923', ref:'1.4', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of science-related claims in communicated information',
    bigIdea:'Someone on the internet says something science-y. Work out whether it actually holds up.',
    format:'End-of-year examination. You are given communicated information — articles, advertisements, posts — containing science-related claims, and asked to evaluate them.',
    evidence:'The specific claim quoted, the science behind it explained accurately, and the evaluation supported by reference to the source and the evidence it offers.',
    criteria:{achieved:'Describe science-related claims in the information and the science relevant to them.',
      merit:'Explain the science behind the claims and whether the information supports them.',
      excellence:'Evaluate the claims comprehensively, justifying your judgement with reference to the science and the source.'},
    bandShift:{aToM:'Explain the actual science behind the claim, so your judgement rests on science rather than impression.',
      mToE:'Evaluate the source as well as the claim — who made it, what evidence they offer, what they leave out.'},
    verbs:['identify','describe','explain','evaluate'],
    topics:['Identifying a science-related claim','The science behind a claim','Evidence quality','Source purpose and reliability','Correlation and causation in reporting','Misleading use of data and graphs','Reaching a justified judgement'],
    contexts:['Communicated information supplied in the examination — you cannot revise the material, only the skills'],
    misconceptions:['Judging a claim by whether it sounds plausible rather than by the science.',
      'Assuming anything quoting a scientist or a study is reliable.',
      'Treating a correlation reported in media as a demonstrated cause.'],
    pitfalls:['The claim evaluated with no science explained behind it.',
      'General criticism of the source with no reference to its specific claims.',
      'Answering from prior knowledge instead of the material supplied.'] }
  ]},

'Chemistry and Biology':{
  lens:'Level 1 ChemBio combines living systems and chemical systems: microorganisms and their environment, chemical reactions, genetic variation, and the physical properties of materials. It is the Level 1 pathway into both Biology and Chemistry.',
  discipline:'Chemistry and Biology explain at more than one level at once — particle, cell, organism, system. A Level 1 answer names the mechanism and links what happens underneath to what you can observe.',
  verifyNote:'Four standards, 20 credits — two internal (5 and 6 credits) and two external (5 and 4 credits). Note the credits are NOT all 5 in this subject.',
  standards:[
  { code:'92020', ref:'1.1', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of the relationship between a microorganism and the environment',
    bigIdea:'Something too small to see, shaping an environment you can. Show how the microorganism and its surroundings affect each other.',
    format:'Internally assessed. Your kaiako may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'The microorganism named specifically, the environmental conditions described with actual values where possible, and the relationship shown working in both directions.',
    criteria:{achieved:'Describe the relationship between the microorganism and its environment.',
      merit:'Explain how the microorganism and the environment affect each other.',
      excellence:'Explain comprehensively — link the biology to the wider effects on the environment or on people.'},
    bandShift:{aToM:'Explain the mechanism — how the conditions affect the microorganism and how it changes its environment in turn.',
      mToE:'Connect the relationship to its wider consequences for the ecosystem, an industry, or human health.'},
    verbs:['describe','explain','discuss'],
    topics:['Types of microorganism','Conditions for growth: temperature, pH, moisture, nutrients','Respiration and fermentation','Decomposition and nutrient cycling','Microorganisms in food and industry','Microorganisms and disease','Effects on the environment'],
    contexts:['A microorganism and environment agreed with your kaiako — often bread, yoghurt, compost, or a waterway'],
    misconceptions:['Assuming all microorganisms are harmful.',
      'Treating the relationship as one-way, when the environment shapes the microorganism and the microorganism changes the environment.',
      'Confusing bacteria, fungi and viruses as if they behaved the same way.'],
    pitfalls:['The microorganism named only by group rather than specifically.',
      'Conditions described without figures.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92021', ref:'1.2', credits:6, mode:'internal', verified:true,
    title:'Demonstrate understanding of chemical reactions in context',
    bigIdea:'What is actually happening when substances react — and why it matters in the real situation you are studying.',
    format:'Internally assessed, and at 6 credits the largest standard in this subject. Your kaiako may only give general feedback during the assessment.',
    evidence:'Word and symbol equations, observations of the reaction, and the chemistry linked to the real context rather than described in isolation.',
    criteria:{achieved:'Describe chemical reactions in the context, including equations.',
      merit:'Explain the reactions and what is happening at particle level.',
      excellence:'Explain comprehensively — link the chemistry to the context and to the effects it produces.'},
    bandShift:{aToM:'Explain what the particles are doing, not just what you can observe.',
      mToE:'Link the particle-level chemistry to the real context and its consequences.'},
    verbs:['describe','explain','write equations'],
    topics:['Types of reaction: combustion, acid-base, precipitation, oxidation','Word and symbol equations','Balancing equations','Signs a reaction has occurred','Rate of reaction and factors affecting it','Particle-level explanations','Chemistry in everyday contexts'],
    contexts:['A chemical context agreed with your kaiako — often corrosion, cooking, water treatment or fuels'],
    misconceptions:['Describing what you can see and calling it an explanation — the particle level is where the explanation lives.',
      'Thinking a substance disappears in a reaction rather than being rearranged.',
      'Confusing a chemical change with a physical one.'],
    pitfalls:['Equations unbalanced or missing.',
      'Observations recorded with no chemistry explaining them.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92022', ref:'1.3', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of genetic variation in relation to an identified characteristic',
    bigIdea:'Why individuals differ — where the variation comes from, and how it passes on.',
    format:'End-of-year examination. You are given a characteristic to work with and asked about the genetics behind its variation.',
    evidence:'Correct genetic notation, Punnett squares set out properly, and the source of the variation named and explained.',
    criteria:{achieved:'Describe genetic variation in relation to the characteristic.',
      merit:'Explain how the variation arises and how it is inherited.',
      excellence:'Explain comprehensively — link the sources of variation to inheritance and to variation in a population.'},
    bandShift:{aToM:'Explain HOW the variation arises and is passed on, rather than describing that individuals differ.',
      mToE:'Link the genetics of the individual to variation across a population.'},
    verbs:['identify','describe','explain'],
    topics:['DNA, genes and alleles','Dominant and recessive alleles','Genotype and phenotype','Punnett squares','Meiosis and variation','Mutation','Environmental influence on phenotype','Variation in populations'],
    contexts:['A characteristic supplied in the examination'],
    misconceptions:['Confusing genotype with phenotype.',
      'Believing mutations arise because an organism needs them.',
      'Assuming every characteristic is controlled by a single gene.',
      'Thinking dominant means most common.'],
    pitfalls:['Punnett squares drawn without stating the genotypes and phenotypes they produce.',
      'Variation described but its source never explained.',
      'Genetic terms used loosely or interchangeably.'] },

  { code:'92023', ref:'1.4', credits:4, mode:'external', verified:true,
    title:'Demonstrate understanding of how the physical properties of materials inform their use',
    bigIdea:'Why things are made of what they are made of — properties, structure, and fitness for purpose.',
    format:'End-of-year examination, and at 4 credits the smallest standard in this subject.',
    evidence:'Named materials with specific measured properties, linked to specific uses, with the structure behind each property explained.',
    criteria:{achieved:'Describe physical properties of materials and how they inform their use.',
      merit:'Explain how the properties arise from structure and why they suit the use.',
      excellence:'Explain comprehensively — compare materials and justify which is best suited to a use.'},
    bandShift:{aToM:'Explain WHY the material has that property — what its structure is doing — and why that suits the use.',
      mToE:'Compare materials for a use and justify which is best suited, including trade-offs.'},
    verbs:['identify','describe','explain','compare'],
    topics:['Physical properties: strength, density, conductivity, melting point, flexibility','Structure and bonding at particle level','Metals, polymers, ceramics and composites','Matching material to purpose','Trade-offs in material choice','Sustainability of materials'],
    contexts:['Materials and uses supplied in the examination or studied in class'],
    misconceptions:['Treating strong and hard as the same property.',
      'Assuming the best material is the one with the highest value of a property, ignoring cost, mass and durability.',
      'Describing a property without connecting it to structure.'],
    pitfalls:['Properties listed with no link to the actual use.',
      'No particle-level explanation of where the property comes from.',
      'Comparisons made without stating what the material is being compared for.'] }
  ]},

'Physics, Earth and Space Science':{
  lens:'Level 1 PESS combines physical systems with Earth and space systems: human-induced change in the Earth system, investigating a physical phenomenon, the Sun–Earth–Moon system, and energy. It is the Level 1 pathway into Physics and into Earth and Space Science.',
  discipline:'Physics and Earth science reason from a model of the situation to the evidence and back. Name the principle before the numbers, and say what the result means physically.',
  verifyNote:'Four standards, 5 credits each, 20 credits — two internal and two external.',
  standards:[
  { code:'92044', ref:'1.1', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of human-induced change within the Earth system',
    bigIdea:'People are changing the Earth system. Show how one of those changes actually works, from cause through to consequence.',
    format:'Internally assessed. Your kaiako may only give general feedback during the assessment. Evidence can be in te reo Māori, English, or New Zealand Sign Language.',
    evidence:'The change named and located, with data showing it, the mechanism traced through the Earth system, and consequences evidenced.',
    criteria:{achieved:'Describe a human-induced change within the Earth system.',
      merit:'Explain how the human activity produces the change within the system.',
      excellence:'Explain comprehensively — link the change across parts of the Earth system and to its consequences.'},
    bandShift:{aToM:'Explain the mechanism — how the human activity actually produces the change — rather than stating that it does.',
      mToE:'Show the change moving between parts of the Earth system — atmosphere, hydrosphere, geosphere, biosphere — and its consequences.'},
    verbs:['describe','explain','discuss'],
    topics:['Spheres of the Earth system and their interactions','Carbon cycle and climate change','Ocean acidification','Land use change and erosion','Water quality','Feedback loops','Evidence for human-induced change','Kaitiakitanga and responses'],
    contexts:['A human-induced change agreed with your kaiako, often local'],
    misconceptions:['Treating the parts of the Earth system as separate rather than connected.',
      'Confusing weather with climate.',
      'Assuming a change is human-induced without evidence distinguishing it from natural variation.'],
    pitfalls:['The change described with no mechanism explained.',
      'No data or figures showing the change.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92045', ref:'1.2', credits:5, mode:'internal', verified:true,
    title:'Demonstrate understanding of a physical phenomenon through investigation',
    bigIdea:'Investigate something physical yourself, and explain what your results actually show about the physics.',
    format:'Internally assessed practical investigation. Your kaiako may only give general feedback during the assessment.',
    evidence:'Your own data with repeats, processed and graphed appropriately, and the pattern explained using physics ideas.',
    criteria:{achieved:'Investigate a physical phenomenon and describe the findings.',
      merit:'Explain the findings using physics ideas.',
      excellence:'Explain comprehensively — link the findings to the physics and discuss the reliability of the investigation.'},
    bandShift:{aToM:'Explain the pattern in your data using physics, rather than describing what the numbers did.',
      mToE:'Link the findings to the underlying physics and judge how much your data can support.'},
    verbs:['investigate','measure','describe','explain'],
    topics:['Aim and variables','Fair testing and controls','Repeats and averaging','Graphing results','Identifying a relationship','Explaining with physics ideas','Reliability and sources of error'],
    contexts:['A physical phenomenon agreed with your kaiako — often motion, light, heat, sound or electricity'],
    misconceptions:['Treating an unexpected result as a mistake rather than as data.',
      'Confusing the independent and dependent variables.',
      'Believing more decimal places means a more accurate measurement.'],
    pitfalls:['Too few repeats to say anything about reliability.',
      'Graphs without labelled axes or units.',
      'Note: this is assessed work. NZQA requires any use of generative AI to be acknowledged, and your kaiako sets what use is acceptable — ask before you use it.'] },

  { code:'92046', ref:'1.3', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of the effect on the Earth of interactions between the Sun and the Earth-Moon system',
    bigIdea:'Day, night, seasons, tides, eclipses — all of it comes from three bodies moving in relation to each other.',
    format:'End-of-year examination. Diagrams are often the clearest way to show these relationships, so practise drawing and annotating them.',
    evidence:'Clear annotated diagrams showing the positions and motions involved, with the effect explained from the geometry.',
    criteria:{achieved:'Describe interactions between the Sun and the Earth-Moon system and their effects on Earth.',
      merit:'Explain how the interactions produce the effects.',
      excellence:'Explain comprehensively — link the geometry and motion to the pattern of effects observed on Earth.'},
    bandShift:{aToM:'Explain how the positions and motions PRODUCE the effect, rather than describing what we observe.',
      mToE:'Link the geometry to the pattern — why the effect varies through the year, the month, or with latitude.'},
    verbs:['identify','describe','explain'],
    topics:['Earth\u2019s rotation and day and night','Earth\u2019s tilt and the seasons','Phases of the Moon','Solar and lunar eclipses','Tides and the Moon','Māori lunar calendar — maramataka','Matariki and the Māori new year'],
    contexts:['The Sun–Earth–Moon system; questions may be set in Aotearoa or Pacific contexts'],
    misconceptions:['Thinking the seasons are caused by Earth\u2019s distance from the Sun rather than by its tilt.',
      'Believing the Moon has a dark side that never receives sunlight.',
      'Assuming eclipses would happen every month if the orbits were in the same plane.',
      'Confusing the Moon\u2019s phases with Earth\u2019s shadow falling on it.'],
    pitfalls:['Diagrams drawn without labels, scale or direction of motion.',
      'Effects described without the geometry that causes them.',
      'Southern Hemisphere seasons and Moon orientation reversed from Northern Hemisphere textbooks.'] },

  { code:'92047', ref:'1.4', credits:5, mode:'external', verified:true,
    title:'Demonstrate understanding of a physical system using energy concepts',
    bigIdea:'Follow the energy — where it starts, what it becomes, and what gets wasted along the way.',
    format:'End-of-year examination. Show working for any calculations, with units.',
    evidence:'Energy stores and transfers named correctly, calculations shown with units, and efficiency losses accounted for rather than ignored.',
    criteria:{achieved:'Describe a physical system using energy concepts, including calculations.',
      merit:'Explain the energy transfers and transformations within the system.',
      excellence:'Explain comprehensively — account for efficiency and energy losses across the whole system.'},
    bandShift:{aToM:'Explain what happens to the energy at each stage, rather than naming the stores involved.',
      mToE:'Account for the whole system including where energy is lost, and use that to explain efficiency.'},
    verbs:['identify','describe','calculate','explain'],
    topics:['Energy stores: kinetic, gravitational potential, elastic, thermal, chemical','Energy transfers and transformations','Conservation of energy','Work and power','Efficiency and wasted energy','Energy in electrical circuits','Renewable and non-renewable energy sources'],
    contexts:['A physical system supplied in the examination or studied in class'],
    misconceptions:['Saying energy is "used up" rather than transferred or dissipated.',
      'Confusing energy with force or with power.',
      'Believing a system can be 100 percent efficient.',
      'Treating heat as a substance rather than as energy transferred.'],
    pitfalls:['Calculations without units or working shown.',
      'Energy transfers described without naming the stores.',
      'Wasted energy ignored, which is usually where the higher grades sit.'] }
  ]}

};

window.NCEA_DATA = window.NCEA_DATA || {};
window.NCEA_DATA['1'] = {
  meta: { qualification:'NCEA', stage:'Level 1', year:2026 },
  faculties: FACULTIES,
  subjects: SUBJECTS
};

})();
